### ISSUE TITLE
No underground villages generating with William Wyther's datapack

### ISSUE THREAD

**Issue by AttilaPapp** [TheGrimsey/Stoneholm#5]
**Describe the bug**
Underground villages do not generate with the datapacks installed below.

**To Reproduce**
Install these datapacks:

https://www.planetminecraft.com/data-pack/william-wythers-overhauled-overworld/
https://www.planetminecraft.com/data-pack/william-wythers-caves-and-cliffs-add-on-for-overhauled-overworld-1-17/

**Expected behavior**
Underground villages should generate

**Mod version:**

stoneholm-1.2.7.jar

**Fabric API version:**

fabric-api-0.35.2+1.17.jar

**Minecraft version:**

1.17

**Screenshots**

**Additional Context:**
Cave Biomes mod and Cavebiomes API mod are working without any problems, generating underground features.

**Comment by 593shaun** [comment]
I can't speak on the datapack, but there's a version of William Wyther's Overhauled Overworld that's a full mod, and that doesn't impact the worldgen from other mods as far as I can tell. It would at least solve your issue.

**Comment by TheGrimsey** [comment]
Hmmm. Odd. Since the Caves & Cliffs datapack works I would assume other worldgen datapacks would also work.

I am not sure what they would be doing differently. Unless they are messing with sea level which Stoneholm uses to determine if it is too high up to spawn (something I am likely gonna be adjusting that in a future update)

**Comment by TheGrimsey** [comment]
This is due to how the data pack works. Use the mod version instead.
